name: '@headlessng/primitives - check'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  id-token: write
  pull-requests: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint source
        run: npm run primitives:lint

      - name: Test source
        run: npm run primitives:test:report

      - name: Report test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 'test results'
          path: reports/packages/@headlessng-primitives/results.xml
          reporter: jest-junit

      - name: Report code coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          badge: true
          filename: reports/packages/@headlessng-primitives/coverage.xml
          format: markdown
          output: both

      - name: Publish coverage report to the pull request comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Build source
        run: npm run primitives:build
