name: '@headlessng/primitives - release'

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint source
        run: npm run primitives:lint

      - name: Test source
        run: npm run primitives:test

      - name: Report test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 'test results'
          path: reports/packages/@headlessng-primitives/results.xml
          reporter: jest-junit

      - name: Report code coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          badge: true
          filename: reports/packages/@headlessng-primitives/coverage.xml
          format: markdown
          output: both

      - name: Build source
        run: npm run primitives:build

      - name: Publish package
        run: npm publish --provenance --access public
        working-directory: dist/packages/@headlessng-primitives
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
